# version: "3.9"

services:

  # ---------- API Gateway ----------
  apigateway-service:
    build: ./apigateway-service
    container_name: apigateway-service
    ports:
      - "${APIGATEWAY_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    depends_on:
      - auth-service
    networks:
      - microservices-net
    restart: unless-stopped


  # # ---------- AUTH SERVICE ----------
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "${AUTHSERVICE_PORT:-8091}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    networks:
      - microservices-net
    restart: unless-stopped


  # ---------- PRODUCT SERVICE ----------
  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "${PRODUCTSERVICE_PORT:-8082}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    networks:
      - microservices-net
    restart: unless-stopped


  # ---------- ORDER SERVICE ----------
  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "${ORDERSERVICE_PORT:-8083}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    networks:
      - microservices-net
    restart: unless-stopped


  # # ---------- PAYMENT SERVICE ----------
  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "${PAYMENT_PORT:-8084}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    networks:
      - microservices-net
    restart: unless-stopped


  # # ---------- USER SERVICE ----------
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "${USERSERVICE_PORT:-8085}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    networks:
      - microservices-net
    restart: unless-stopped


  # # ---------- ADMIN SERVICE ----------
  admin-service:
    build: ./services/admin-service
    container_name: admin-service
    ports:
      - "${ADMINSERVICE_PORT:-8086}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    networks:
      - microservices-net
    restart: unless-stopped


  # # ---------- FILE SERVICE ----------
  file-service:
    build: ./services/file-service
    container_name: file-service
    ports:
      - "${FILESERVICE_PORT:-8087}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    networks:
      - microservices-net
    restart: unless-stopped


  # # ---------- NOTIFICATION SERVICE ----------
  notification-service:
    build: ./services/notificaiton
    container_name: notification-service
    ports:
      - "${NOTIFICATION_PORT:-8088}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    networks:
      - microservices-net
    restart: unless-stopped


networks:
  microservices-net:
    driver: bridge